confirmOnQuit: false
os:
  editPreset: 'nvim-remote'
gui:
  expandFocusedSidePanel: true
  showFileTree: true
  showBottomLine: false
  showCommandLog: false
  showRandomTip: false
  border: rounded
  nerdFontsVersion: '3'
  filterMode: fuzzy
  commitLength:
    show: true
  theme:
    cherryPickedCommitBgColor: [default]
    markedBaseCommitBgColor: []
    markedBaseCommitFgColor: [bold]
    selectedLineBgColor: [underline]
git:
  pagers:
    - colorarg: always
      pager: delta --paging=never --hunk-header-style=omit --file-decoration-style=ul
  mainBranches:
    - master
    - main
    - preprod
    - devel
  log:
    showGraph: always
    format: oneline
  branchLogCmd: git log --graph --color=always --pretty='%Cgreen%h %Cblue%an (%ar) %Creset%s' {{branchName}} --
  autoFetch: false
  fetchAll: true
  overrideGpg: true
  showWholeFileDiff: false
